apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: frijugsincek/users:2020-12-03-04-24-45
          name: users
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/sdbifqsd
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: sdbifqsd
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: vnesi-geslo
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---


#apiVersion: v1
#kind: Service
#metadata:
#  name: users
#spec:
#  type: ClusterIP
#  ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: server
#  selector:
#    app: users

apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - name: web
      port: 8080
  type: ClusterIP