kumuluzee:
  name: users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://localhost:5432/users
      username: dbuser
      password: postgres
      pool:
        max-size: 3
  cors-filter:
      servlet:
        allow-origin: "http://localhost:4200"
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDS
  metrics:
    web-instrumentation:
      - name: users-endpoint
        url-pattern: /v1/users/*
  config:
    consul:
#      agent: http://40.88.21.225:80
      agent: http://localhost:8500
rest-properties:
  maintenance-mode: false
  broken: false
